### PR TITLE
add schema to config

### PR DESCRIPTION
**Pull request by valentimlh**
added schema configuration to connection, to use with postgresql or whatever other db engine that uses schema methods.

### CODE REVIEW

**Comment by duayres** [comment]
Hello, the tests are not passing. You can solve this by updating the tests and the fixture (Fixtures/config), the same I've done [here](https://github.com/wouterj/WouterJEloquentBundle/pull/70), aided by Wouter.

Can you please fix them?

**Comment by lukevalentim** [comment]
There is a test (last one) I am not able to pass though and I tested dozens of times... Can you help me please?

________________________________
De: Eduardo Ayres <notifications@github.com>
Enviado: Thursday, June 7, 2018 2:05:35 PM
Para: wouterj/WouterJEloquentBundle
Cc: lukevalentim; Author
Assunto: Re: [wouterj/WouterJEloquentBundle] add schema to config (#92)


Hello, the tests are not passing. You can solve this by updating the tests and the fixture (Fixtures/config), the same I've done here<https://github.com/wouterj/WouterJEloquentBundle/pull/70>, aided by Wouter.

Can you please fix them?

**Comment by duayres** [comment]
I think you were good at b1d0dfa, the deprecations seems to be due to other issues than your modifications, in other words, not caused by you.
I'll call for divine intervention here: @wouterj can you aid us, please? xD

**Comment by wouterj** [comment]
I've continued this PR in #119. I'm sorry for the long wait, this bundle has been at the absolute bottom of my priority list for the past years. Fortunately, with Laravel adapting semantic versioning, I try to pick up support in this bundle again (as it should be much easier to manager).

**Pull request closed without merging**
