### PR TITLE
[Cont'd] Make migration path configurable

### PR DESCRIPTION
**Pull request by wouterj**

### CODE REVIEW

**Comment by theofidry** [comment]
Way simpler than what I had in mind 👍

**Comment by theofidry** [comment]
@wouterj what about adding this to the Configuration as well?

Besides the doc needs to be updated: there is no mention of this new parameter and I think [this section](https://github.com/wouterj/WouterJEloquentBundle/blob/master/resources/docs/migrations.rst#how-to-configure-migration-paths-in-a-bundle) in the doc is outdated.

**Comment by wouterj** [comment]
> @wouterj what about adding this to the Configuration as well?

Laravel doesn't allow to configure it, but as Symfony is doing configuration over convention, I guess it makes sense to create a setting for this.

 > Besides the doc needs to be updated: there is no mention of this new parameter and I think this section in the doc is outdated.

It's hyper up-to-date and documenting a new feature in the master branch: https://github.com/wouterj/WouterJEloquentBundle/pull/36

**Comment by theofidry** [comment]
>It's hyper up-to-date and documenting a new feature in the master branch: #36

Hm I see, maybe we should function that parameter there as well then?

**Pull request merged**
