### PR TITLE
Add support for Symfony 6/Laravel 9

### PR DESCRIPTION
**Pull request by wouterj**
Laravel 9 is the first version that comes with support for Symfony 6 and is expected to be released [in January](https://blog.laravel.com/laravel-9-release-date).

### CODE REVIEW

**Comment by Broutard** [comment]
With SF6 I get a "Call to a member function has() on null" in the Db Facade.
The Facade seems to not have set the container.

**Comment by Broutard** [comment]
Hi,

When running `make:eloquent-migration create_base_table` got:

```Too few arguments to function Illuminate\Database\Migrations\MigrationCreator::firePostCreateHooks(), 1 passed in /opt/app/src/vendor/wouterj/eloquent-bundle/src/Migrations/Creator.php on line 43 and exactly 2 expected```

**Comment by Broutard** [comment]
When running `eloquent:migrate` got:

```Call to a member function getRequire() on null```

Since Laravel8, we have to extends resolvePath() method in `Migrator` class also to avoid `$migration = $this->files->getRequire($path);` call.

```
/**
     * Resolve a migration instance from a migration path.
     *
     * @param  string  $path
     * @return object
     */
    protected function resolvePath(string $path)
    {
        $class = $this->getMigrationClass($this->getMigrationName($path));

        if (class_exists($class) && realpath($path) == (new ReflectionClass($class))->getFileName()) {
            return new $class;
        }

        $migration = require $path;

        return is_object($migration) ? $migration : new $class;
    }
    ```

**Comment by wouterj** [comment]
Hi @Broutard. Thank you for testing out this PR! I've tried to fix your first comment.

If I'm understand your second comment correctly, this is also a bug in the current release of this bundle? If so, could you maybe sent a new PR with a fix? (and if possible a test case for the fix) Thank you! :)

**Comment by Broutard** [comment]
@wouterj for the 2nd, the bug should appear also with Laravel8 (not tested)

**Comment by fd6130** [comment]
So we will have a new release version of this bundle after Larevel 9 is released?

**Comment by wouterj** [comment]
Yes, I'm trying to keep up with Laravel releases. Depending on the available time, a new version will be released in the days/weeks after the Laravel release.

**Comment by g-ra** [comment]
which news guys ? i have same error

**Comment by g-ra** [comment]
Here is my fix code 

in Service

namespace App\Service;

use WouterJ\EloquentBundle\Migrations\Migrator as BaseMigrator;
use ReflectionClass;

class CustomMigrator extends BaseMigrator
{
    protected function resolvePath(string $path)
    {
        $class = $this->getMigrationClass($this->getMigrationName($path));

        if (class_exists($class) && realpath($path) === (new ReflectionClass($class))->getFileName()) {
            return new $class;
        }

        $migration = require $path;

        return is_object($migration) ? $migration : new $class;
    }
}


in eloquent.yaml
`services:
    wouterj_eloquent.migrator:
        class: App\Service\CustomMigrator
        arguments:
            - '@wouterj_eloquent.migrations.repository'
            - '@wouterj_eloquent.database_manager'`

**Pull request merged**
